# Generated by Django 4.0.2 on 2022-02-09 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_parent_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='firstname',
        ),
    ]
