# Generated by Django 4.0.2 on 2022-02-09 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_first_name_student_firstname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='firstname',
            new_name='first_name',
        ),
    ]
