# Generated by Django 4.0.2 on 2022-02-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_firstname_student_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='parent_contact_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='contact_no',
            field=models.BigIntegerField(),
        ),
    ]
