# Generated by Django 4.0.2 on 2022-02-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_parent_parent_contact_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
